/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/app-check': RouteRecordInfo<'/app-check', '/app-check', Record<never, never>, Record<never, never>>,
    '/authentication': RouteRecordInfo<'/authentication', '/authentication', Record<never, never>, Record<never, never>>,
    '/config': RouteRecordInfo<'/config', '/config', Record<never, never>, Record<never, never>>,
    '/converter-with-number': RouteRecordInfo<'/converter-with-number', '/converter-with-number', Record<never, never>, Record<never, never>>,
    '/nested-collections': RouteRecordInfo<'/nested-collections', '/nested-collections', Record<never, never>, Record<never, never>>,
    '/nested-refs-list': RouteRecordInfo<'/nested-refs-list', '/nested-refs-list', Record<never, never>, Record<never, never>>,
    '/pinia-store': RouteRecordInfo<'/pinia-store', '/pinia-store', Record<never, never>, Record<never, never>>,
    '/rtdb-todos': RouteRecordInfo<'/rtdb-todos', '/rtdb-todos', Record<never, never>, Record<never, never>>,
    '/storage': RouteRecordInfo<'/storage', '/storage', Record<never, never>, Record<never, never>>,
    '/todos': RouteRecordInfo<'/todos', '/todos', Record<never, never>, Record<never, never>>,
    '/vuex-store': RouteRecordInfo<'/vuex-store', '/vuex-store', Record<never, never>, Record<never, never>>,
  }
}
